import { faker } from "@faker-js/faker";
const products = [
  {
    id: faker.random.numeric(5),
    name: "Apple Watch",
    model: "Series 5 SE",
    imgURL: require("./assets/images/apple-watch.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Sony ZX33OBT",
    model: "Light Gray",
    imgURL: require("./assets/images/headphones.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Serious Black",
    imgURL: require("./assets/images/iphone-12-01.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Subway Blue",
    imgURL: require("./assets/images/iphone-12-02.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Dell XPS 13",
    model: "Midnight Gray",
    imgURL: require("./assets/images/Dell-XPS-13-Black.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Product RED",
    imgURL: require("./assets/images/iphone-12-03.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Milky White",
    imgURL: require("./assets/images/iphone-12-04.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },

  {
    id: faker.random.numeric(5),
    name: "Iphone 12",
    model: "Rose Pink",
    imgURL: require("./assets/images/iphone-12-Pro-01.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Dell XPS 15",
    model: "Light Gray",
    imgURL: require("./assets/images/Dell-XPS-15-Black.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 12",
    model: "Navy Blue",
    imgURL: require("./assets/images/iphone-12-Pro-02.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 13 Pro",
    model: "Silly Silver",
    imgURL: require("./assets/images/iphone-13-Pro-01.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 13 Pro",
    model: "Grey",
    imgURL: require("./assets/images/iphone-13-Pro-02.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Samsung Galaxy Note 21",
    model: "2-options",
    imgURL: require("./assets/images/samsung-Note21.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Samsung Galaxy S21+",
    model: "Lilac Purple",
    imgURL: require("./assets/images/samsung-S21-Pro.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Samsung Galaxy S21",
    model: "Lilac Purple",
    imgURL: require("./assets/images/samsung-S21.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
  {
    id: faker.random.numeric(5),
    name: "Dell XPS 13",
    model: "White",
    imgURL: require("./assets/images/Dell-XPS-13-White.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
    countOfProduct: 0,
  },
];
export default products;
